version: '3'
services:
  helios:
    build:
      context: .
    container_name: helios
    volumes:
      - ./helios.yml:/config/helios.yml
      - ./data.json:/config/data.json
    ports:
      - 8000:8000
