name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/docker-hub-build-and-push.yml@main
    secrets: inherit
    with:
      image: helios
      repository: haumea
      context: .
      file: Dockerfile
