name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/docker-build-and-push.yml@main
    secrets: inherit
    with:
      REGISTRY: docker-hub
      IMAGE_NAME: helios
      REPOSITORY: haumea
      BUILD_CONTEXT: .
      DOCKERFILE: Dockerfile
